import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
export type Item = { id:string; title:string; done?:boolean; date?:string; category?:string; amount?:number; progress?:number; body?:string };
export type Data = { tasks:Item[]; appointments:Item[]; expenses:Item[]; habits:Item[]; goals:Item[]; notes:Item[]; theme:'light'|'dark'; language:'ar'|'fr'; profile:string };
const seed:Data={tasks:[{id:'1',title:'مراجعة خطة المشروع',done:false,date:'2026-09-21',category:'عمل'},{id:'2',title:'التمرين الصباحي',done:true,date:'2026-09-20',category:'شخصي'}],appointments:[{id:'1',title:'اجتماع الفريق',date:'2026-09-22',category:'14:00'}],expenses:[{id:'1',title:'مشتريات المنزل',amount:150,date:'2026-09-19',category:'المنزل'}],habits:[{id:'1',title:'القراءة',done:true,progress:80},{id:'2',title:'التمرين',done:false,progress:60}],goals:[{id:'1',title:'التعلم',progress:70,date:'2026-10-15'}],notes:[{id:'1',title:'أفكار المشروع',body:'اكتب أفكارك هنا.',date:'2026-09-19'}],theme:'light',language:'ar',profile:'مستخدم مِنظَّم'};
const key='mounadim-data';
const read=():Data=>{try{return {...seed,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return seed}};
type Ctx=Data&{add:(kind:keyof Pick<Data,'tasks'|'appointments'|'expenses'|'habits'|'goals'|'notes'>,item:Item)=>void; update:(kind:string,id:string,item:Item)=>void; remove:(kind:string,id:string)=>void; setPrefs:(v:Partial<Data>)=>void; reset:()=>void; exportData:()=>void; importData:(text:string)=>boolean};
const Context=createContext<Ctx|null>(null);
export function Store({children}:{children:ReactNode}){const [data,setData]=useState<Data>(read);useEffect(()=>{localStorage.setItem(key,JSON.stringify(data));document.documentElement.dataset.theme=data.theme;document.documentElement.dir=data.language==='ar'?'rtl':'ltr';document.documentElement.lang=data.language},[data]);
const value=useMemo<Ctx>(()=>({...data,add:(kind,item)=>setData(d=>({...d,[kind]:[...(d[kind] as Item[]),item]})),update:(kind,id,item)=>setData(d=>({...d,[kind]:(d[kind] as Item[]).map(x=>x.id===id?item:x)})),remove:(kind,id)=>setData(d=>({...d,[kind]:(d[kind] as Item[]).filter(x=>x.id!==id)})),setPrefs:v=>setData(d=>({...d,...v})),reset:()=>setData(seed),exportData:()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='mounadim-backup.json';a.click()},importData:t=>{try{const x=JSON.parse(t);if(!x.tasks||!x.settings&&false)return false;setData(d=>({...d,...x}));return true}catch{return false}}}),[data]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useStore=()=>{const x=useContext(Context);if(!x)throw Error('Store missing');return x};
